name: 'Setup Elixir Environment'
description: 'Sets up Elixir and installs dependencies'

runs:
  using: "composite"
  steps:
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        otp-version: "27.1"
        elixir-version: "1.17.3"

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install O/S deps
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libmnl-dev libnl-3-dev libnl-genl-3-dev

    - name: Install packages
      shell: bash
      run: |
        mix archive.install hex nerves_bootstrap --force
        mix local.hex --force
        mix local.rebar --force

    - name: Install dependencies
      shell: bash
      run: |
        mix deps.get
        MIX_TARGET=rpi4 mix deps.get
        MIX_TARGET=rpi4_kiosk mix deps.get