# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      ImageOS: ubuntu22
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-elixir

      - name: lint - credo
        run: |
          mix credo --strict
          MIX_TARGET=rpi4 mix credo --strict
          MIX_TARGET=rpi4_kiosk mix credo --strict

      - name: lint - dialyzer
        run: |
          mix dialyzer
          MIX_TARGET=rpi4 mix dialyzer
          MIX_TARGET=rpi4_kiosk mix dialyzer

      - name: Run tests
        run: mix test
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-elixir

      - name: Deploy static assets
        run: mix assets.deploy

      - name: Build Kiosk Firmware
        run: |
          MIX_ENV=prod MIX_TARGET=rpi4_kiosk mix deps.get
          MIX_ENV=prod MIX_TARGET=rpi4_kiosk mix firmware --output "open_boss_rpi4_kiosk-${{ github.ref_name }}.fw"

      - name: Build Pi4 Firmware
        run: |
          MIX_ENV=prod MIX_TARGET=rpi4 mix deps.get
          MIX_ENV=prod MIX_TARGET=rpi4 mix firmware --output "open_boss_rpi4-${{ github.ref_name }}.fw"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: |
            open_boss_rpi4_kiosk-${{ github.ref_name }}.fw
            open_boss_rpi4-${{ github.ref_name }}.fw
          generate_release_notes: true
