# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      ImageOS: ubuntu22
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-elixir

      - name: lint - credo
        run: |
          mix credo --strict
          MIX_TARGET=rpi4 mix credo --strict
          MIX_TARGET=rpi4_kiosk mix credo --strict

      - name: lint - dialyzer
        run: |
          mix dialyzer
          MIX_TARGET=rpi4 mix dialyzer
          MIX_TARGET=rpi4_kiosk mix dialyzer

      - name: Run tests
        run: mix test
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-elixir

      - name: Build Release Package 1
        run: 'echo "TODO: Add commands to build first release package"'

      - name: Build Release Package 2
        run: 'echo "TODO: Add commands to build second release package"'

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          files: |
            package1.tar.gz
            package2.tar.gz
          generate_release_notes: true
